### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by makanbaks0** [gmazoyer/looking-glass#138]
Hi, every time I run this using `php -S 192.168.1.1:8000`.

I had no output after input device, command (ping), IP and press enter.

Log from PHP:
```
[Wed Sep 16 15:29:09 2020] PHP Notice:  Connection closed prematurely in /looking-glass/libs/phpseclib-2.0.29/Net/SSH2.php on line 3936
```
I already chaged phpseclib to version 2.0.29, because phpseclib version 2.0.23 had the same issue.

Log from /var/log/looking-glass.log:
```
[2020-09-16 15:29:09] [client: 192.168.1.1] 10.0.0.1 > [BEGIN]  ping -c 10  -a  10.0.0.1 10.0.0.2



[2020-09-16 15:29:16] [client: 192.168.1.1] 10.0.0.1 > [END]  ping -c 10  -a  10.0.0.1 10.0.0.2
```
It had space between BEGIN and END.

Log from device:
```
User   : lg, VT0, 192.168.1.1
Time   : 2020-09-16 15:29:09
Command:  ping -c 10  -a  10.0.0.1 10.0.0.2
```
It's successfully connected to device and run a command. 

Any solution?
Thanks.

**Comment by neilschelly** [comment]
You might want to check my comments on #103 for a workaround that helps me.
