### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ServerionNL** [gmazoyer/looking-glass#151]
Hi,

I cloned the files using git and running PHP 7.2 (and tried PHP 7.4) but after install I get:

`[Thu Mar 11 13:16:10.032544 2021] [php7:error] [pid 5798] [client 185.126.34.40:0] PHP Fatal error:  Uncaught Error: Call to undefined function int() in /home/xxxxx/domains/xxxxx/public_html/new/index.php:151\nStack trace:\n#0 /home/xxxxx/domains/xxxx/public_html/new/index.php(310): LookingGlass->render_header()\n#1 /home/xxxx/domains/xxxx/public_html/new/index.php(331): LookingGlass->render()\n#2 {main}\n  thrown in /home/xxxxx/domains/xxxxx/public_html/new/index.php on line 151`

Tried 3 different webservers already...

**Comment by ServerionNL** [comment]
I just noticed an update, re-cloned and works now...

**Comment by gmazoyer** [comment]
Indeed, fixed in c70828f thanks for reporting the issue.
