### ISSUE TITLE
Change SSH Connection port

### ISSUE THREAD

**Issue by ServerionNL** [gmazoyer/looking-glass#152]
Is there any way to set the SSH Port when connecting to a router? We are not using 22 by default.

We tried

`$config['routers']['router1']['host'] = 'rtr001name:555';`

and 

`$config['routers']['router1']['host'] = 'rtr001name 555';`

and 

`$config['routers']['router1']['host'] = 'rtr001name';
$config['routers']['router1']['port'] = '555';`

But without any luck !

**Comment by gmazoyer** [comment]
You should use:

```php
$config['routers']['router1']['port'] = 555;
```

Without double or single quotes. The value must be an PHP integer.
