### ISSUE TITLE
How to add additional commands?

### ISSUE THREAD

**Issue by warriorsoul15** [gmazoyer/looking-glass#154]
Is this possible? is it documented anywhere..

One useful one off the top of my head would be a generic   show route x.x.x.x   that is not BGP specific,
show ip bgp sum   (summary bgp info including peer status)

showing bgp advertisements or received routes to/from a given peer would be good

OSPF related commands

A better way to self-make these commands would be awesome.   I have actually made a prototype Cisco NXOS version of the existing commands in a new cisco_nxos.php file if you are interested.

**Comment by gmazoyer** [comment]
Not possible for now, see #84.

**Comment by scramatte** [comment]
Hi, 

I'm interested into NXOS support
@warriorsoul15 , can you send me your  cisco_nxos.php file ?

Regards
