### ISSUE TITLE
Demo or Screenshots

### ISSUE THREAD

**Issue by Gunni** [gmazoyer/looking-glass#165]
Hey,

Could anyone provide a link to a public instance, or a demo instance, or screenshots?

Anything at all?

**Comment by rabin-io** [comment]
Look at  https://github.com/gmazoyer/looking-glass/blob/master/docs/our_users.md, but keep in mind that the styling can be customized.

**Comment by Gunni** [comment]
I'd like to point out that the link is dead and the readme still has no screenshots.
