### ISSUE TITLE
Output filters not working

### ISSUE THREAD

**Issue by dmayan-ss** [gmazoyer/looking-glass#167]
Hi,
I have the following filters set in config.php

```
// Things to remove from the output (PHP compatible regex)
$config['filters']['output'][] = '/^login/';
$config['filters']['output'][] = '/^VTY/';
```

However, the ouput of my Huawei VRP router still includes lines with those words:

![image](https://user-images.githubusercontent.com/47798902/187282957-54859770-79ef-4812-b2b2-422a283017df.png)

I also tried with:

```
// Things to remove from the output (PHP compatible regex)
$config['filters']['output'][] = '/^login$/';
$config['filters']['output'][] = '/^VTY$/';
```

And I got the same results.

How can I solve this or what I a doing wrong? Thanks, and sorry for bad english.

**Comment by QDaniel** [comment]
the regex is wrong ^ = Begin of line.
Use:
`$config['filters']['output'][] = '/\slogin\s/';
$config['filters']['output'][] = '/\sVTY\s/';`
