### ISSUE TITLE
VyOS 1.3 

### ISSUE THREAD

**Issue by felbinger** [gmazoyer/looking-glass#169]
On VyOS 1.3, with `type=vyatta`, the `show route ...` commands does not work.

I investigated a bit and found out that the vyatta module is supposed [to run commands in operator mode](https://github.com/gmazoyer/looking-glass/blob/main/routers/vyatta.php#L25). Due to the fact that [Vyatta inherits from Quagga](https://github.com/gmazoyer/looking-glass/blob/main/routers/vyatta.php#L24) the wrong commands are being used:
- `Command: vtysh -c " show ipv6 bgp regexp ^17990_ "`
- `Command: vtysh -c " show ipv4 bgp unicast 1.1.1.1 "`
- `Command: vtysh -c " show ipv6 bgp unicast 2600:: "`

**I fixed the problem by setting `type=frr`**, this way I'm using the vtysh instead of the vyatta operator mode commands.

Maybe it would be a good idea to adjust the documentation regarding how to setup looking-glass for vyos.

**Comment by isnuryusuf** [comment]
i use type=vyos and change quangga.php as follow:

Before:
```
﻿﻿protected function build_bgp($parameter) {
    $cmd = new CommandBuilder();
    // vytsh commands need to be quoted
    $cmd->add(self::$wrapper, '"', 'show');

    if (match_ipv6($parameter, false)) {
      $cmd->add('ipv6');
    }
    if (match_ipv4($parameter, false)) {
      $cmd->add('ipv4');
    }
    $cmd->add('bgp unicast', $parameter, '"');

    return array($cmd);
  }
  ```
  
  Change to:
  ```
  ﻿﻿protected function build_bgp($parameter) {
    $cmd = new CommandBuilder();
    // vytsh commands need to be quoted
    $cmd->add(self::$wrapper, '"', 'show');
    $cmd->add('ip bgp', $parameter, '"');

    if (match_ipv6($parameter, false)) {
      $cmd->add('ipv6 unicast');
    }
    if (match_ipv4($parameter, false)) {
      $cmd->add('ipv4 unicast');
    }
//    $cmd->add('bgp unicast', $parameter, '"');

    return array($cmd);
  }﻿
  
  ```
  
the old code will generate following command:
`Unknown command:  show ip ipv4 bgp unicast 1.1.1.1 `

The valid command should be:
`﻿﻿show ip bgp 1.1.1.1`
or
`﻿﻿show ip bgp ipv4 unicast 1.1.1.1  `

**Comment by felbinger** [comment]
VyOS 1.3 is deprecated now, so no need to add support for lg
