### ISSUE TITLE
30 second delay when querying router

### ISSUE THREAD

**Issue by michelpy** [gmazoyer/looking-glass#179]
There is a 30 second delay between the time clicking 'Enter' and the results are displayed. This does not come from the router, when I ssh manually to it from the looking glass host, results are immediate.
Looks like some kind of a timeout but I can't figure out where it is.

**Comment by gmazoyer** [comment]
The default timeout for command is by default 30 seconds indeed. Do you have a valid output after these 30 seconds? If so, is it a complete output, with all the expected lines?

This could be due to a command that takes more than the timeout to complete.

**Comment by michelpy** [comment]
It works fine, it's just the default 30 second is a little long. I did some digging and found where to change it :

What does not work :

in : includes\config.defaults.php
function set_defaults_for_routers(&$parsed_config) {
  $router_defaults = array(
    'timeout' => 5,

in : config.php
$config['timeout'] = 5;

What does work :

in : config.php
$config['routers']['router1']['timeout'] = 5;

Eventually I will contribute some code that analyzes the router's prompt (e.g. 'router-1>' and returns as soon as it gets it, which means command completion.
