### ISSUE TITLE
Version 2.3.0 is broken

### ISSUE THREAD

**Issue by gondimcodes** [gmazoyer/looking-glass#191]
Hi,
Version 2.3.0 has problems that appear to be related to CSS. It does not format the site correctly and in the code it references a vendor directory, which does not exist.
![looking-glass](https://github.com/gmazoyer/looking-glass/assets/20425009/111d4cd5-3014-4181-b235-412a00dd337f)

**Comment by gmazoyer** [comment]
It is not broken but you have to use [Composer](https://getcomposer.org/) to install dependencies including JS and CSS ones. You can refer to [this line](https://github.com/gmazoyer/looking-glass/blob/main/Dockerfile#L14) in the Dockerfile to see how to use Composer.
