### ISSUE TITLE
Resolving of hostnames not working

### ISSUE THREAD

**Issue by willie058** [gmazoyer/looking-glass#192]
Hi,

I'm encountering an issue when I enter a FQDN with the ping option. I receive the message: "Error unknown host." I suspect it has something to do with permissions or another aspect of my system configuration. Could someone explain how this function works? In the utils.php file, there is a call for the function dns_get_record, but I can't locate the file where the function is defined.

Additionally, I've noticed that the system can resolve domains when I use nslookup or dig. I'm using a non-Docker installation.

Does anyone have insights into how this works?

**Comment by gmazoyer** [comment]
This must be an issue with your installation, maybe due to system permission as you mentioned. the `dns_get_record` is a [built-in function](https://www.php.net/manual/en/function.dns-get-record.php) of PHP.

**Comment by willie058** [comment]
Thank you! Changed something and it is working now.
