### ISSUE TITLE
missing file vendor/autoload.php

### ISSUE THREAD

**Issue by kiaz-github** [gmazoyer/looking-glass#193]
https://github.com/gmazoyer/looking-glass/blob/6908a7a40f0a9ef7850accbf1dee7908d7e7cb58/auth/ssh.php#L22

PHP Fatal error:  Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/looking-glass/auth/ssh.php:22

**Comment by gmazoyer** [comment]
The `vendor` directory is not included on purpose.You have to use [Composer](https://getcomposer.org/) to get the required dependencies including JS and CSS ones. You can refer to [this line](https://github.com/gmazoyer/looking-glass/blob/main/Dockerfile#L14) in the Dockerfile to see how to use Composer.
