### ISSUE TITLE
Missing folder?

### ISSUE THREAD

**Issue by broonu** [gmazoyer/looking-glass#197]
I just installed and my page shows weird, no images and styles and log shows:

A.B.C.D- - [05/Oct/2024:20:54:44 -0300] "GET /vendor/twbs/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 493 "http://lg.mysite/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"

There is no "vendor" folder.

**Comment by rabin-io** [comment]
Did you run `composer install`  which install all the required dependents?

**Comment by broonu** [comment]
> Did you run `composer install` which install all the required dependents?

Hello,

I'm not using docker.

**Comment by rabin-io** [comment]
[composer](https://getcomposer.org/) is not a docker thing, it's PHP package manager.

**Comment by grossstadtmann** [comment]
Hey, Sorry to reopen that issue. I have a local installation and did it in a custom /var/www/looking-glass folder. I executed composer and it created the Vendor folder. But still it can not load the css and js files. What did i do wrong ?

**Comment by gmazoyer** [comment]
> It try to get the files like this:
> 
> `https://domain/libs/bootstrap-5.1.3/css/bootstrap.min.css`

Either you need to clear a cache somewhere or your installation is somehow broken. As you can [see here](https://github.com/gmazoyer/looking-glass/blob/main/index.php#L372-L373), the code does not refer to `libs/` anymore.

**Comment by grossstadtmann** [comment]
Ok i found it. I installed composer from source and not from the packet manager. So i missed zip, unzip and php-zip. It seems it did some executions not right. After reinstalling overhang is fine.

Best regards.
